###########
# site.title, site.url, site.author.name

title:   'Dr. Wei Chen (#CompPhys)'
author:  
  name:  'Wei Chen'
description:  'computational condensed matter physics'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: 
url:  'http://wch3n.github.io/'


########
# more settings

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

